[package]
name = "gardswag-tysy-collect"
description = "type system constraint collector for gardswag"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
gardswag-core.path = "../gardswag-core"

[dependencies.serde]
version = "1.0"
features = ["derive"]
