[package]
name = "gardswag-typesys"
description = "Hindley Milner type system implementation for gardswag"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
thiserror = "1.0"
tracing = "0.1.34"
