[package]
name = "gardswag"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
gardswag-syntax.path = "../gardswag-syntax"
gardswag-typesys.path = "../gardswag-typesys"
thiserror = "1.0"
