[package]
name = "gardswag-syntax"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
thiserror = "1.0"
unicode-normalization = "0.1"
unicode-xid = "0.2"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dev-dependencies]
insta = "1.14"
proptest = "1.0"
