[package]
name = "gardswag-subst"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
gardswag-annotated.path = "../gardswag-annotated"
gardswag-varstack.path = "../gardswag-varstack"
